# Polynomial features
Por Rodolfo Antonio Zea Posadas

In [2]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

# 1 variable de grado 1

In [5]:
x = np.arange(1).reshape(1, 1)
poly = PolynomialFeatures(1)
poly.fit_transform(x)

array([[1., 0.]])

# 2 variables de grado 2

In [6]:
x = np.arange(2).reshape(1, 2)
poly = PolynomialFeatures(2)
poly.fit_transform(x)

array([[1., 0., 1., 0., 0., 1.]])

# 2 variables de grado 3

In [7]:
x = np.arange(2).reshape(1, 2)
poly = PolynomialFeatures(3)
poly.fit_transform(x)

array([[1., 0., 1., 0., 0., 1., 0., 0., 0., 1.]])

# 3 variables grado 1

In [8]:
x = np.arange(3).reshape(1, 3)
poly = PolynomialFeatures(1)
poly.fit_transform(x)

array([[1., 0., 1., 2.]])

# 3 variables grado 2

In [9]:
x = np.arange(3).reshape(1, 3)
poly = PolynomialFeatures(2)
poly.fit_transform(x)

array([[1., 0., 1., 2., 0., 0., 0., 1., 2., 4.]])

# 3 variables grado 3

In [10]:
x = np.arange(3).reshape(1, 3)
poly = PolynomialFeatures(3)
poly.fit_transform(x)

array([[1., 0., 1., 2., 0., 0., 0., 1., 2., 4., 0., 0., 0., 0., 0., 0.,
        1., 2., 4., 8.]])

# 3 variables grado 4

In [11]:
x = np.arange(3).reshape(1, 3)
poly = PolynomialFeatures(4)
poly.fit_transform(x)

array([[ 1.,  0.,  1.,  2.,  0.,  0.,  0.,  1.,  2.,  4.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  2.,  4.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  2.,  4.,  8., 16.]])

# 4 variables grado 4

In [12]:
x = np.arange(4).reshape(1, 4)
poly = PolynomialFeatures(4)
poly.fit_transform(x)

array([[ 1.,  0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,
         6.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.,
        16., 24., 36., 54., 81.]])

# 5 variables grado 5

In [13]:
x = np.arange(5).reshape(1, 5)
poly = PolynomialFeatures(5)
poly.fit_transform(x)

array([[1.000e+00, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        2.000e+00, 3.000e+00, 4.000e+00, 4.000e+00, 6.000e+00, 8.000e+00,
        9.000e+00, 1.200e+01, 1.600e+01, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 4.000e+00, 6.000e+00,
        8.000e+00, 9.000e+00, 1.200e+01, 1.600e+01, 8.000e+00, 1.200e+01,
        1.600e+01, 1.800e+01, 2.400e+01, 3.200e+01, 2.700e+01, 3.600e+01,
        4.800e+01, 6.400e+01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+0

# 6 variables grado 6

In [14]:
x = np.arange(6).reshape(1, 6)
poly = PolynomialFeatures(6)
poly.fit_transform(x)

array([[1.0000e+00, 0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00,
        4.0000e+00, 5.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 2.0000e+00,
        3.0000e+00, 4.0000e+00, 5.0000e+00, 4.0000e+00, 6.0000e+00,
        8.0000e+00, 1.0000e+01, 9.0000e+00, 1.2000e+01, 1.5000e+01,
        1.6000e+01, 2.0000e+01, 2.5000e+01, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
        2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00, 4.0000e+00,
        6.0000e+00, 8.0000e+00, 1.0000e+01, 9.0000e+00, 1.2000e+01,
        1.5000e+01, 1.6000e+01, 2.0000e+01, 2.5000e+01, 8.0000e+00,
        1.2000e+01, 1.6000e+01, 2.0000e+01, 1.8000e+01, 2.4000e+01,
        3.0000e+01, 3.2000e+01, 4.0000e+01, 5.00

# Conclusión

En las pruebas anteriormente realizadas, es posible ver la existencia de la llamada "maldición de la dimensionalidad", que a grandes rasgos, indica que a mayor número de variables o mayor complejidad en el modelo, habrá mayor dispersión entre los datos. Esto se traduce en que las distancias entre los datos dejarán de ser significativas. Esto implica que, para que las distancias entre los datos sean significativas, se requerirá de una gran cantidad de datos, lo que muchas veces no es posible conseguir.

Adicionalmente, si se contara con dicha cantidad de datos, el costo de procesamiento sería altísimo, lo cual haría que el tiempo de procesamiento fuera muy elevado.

Adicionalmente, cuando se tiene un número elevado de features, por lo general, la correlación existente es muy baja para la mayoría de ellas, a tal punto, que muchas veces puede decirse que no existe causalidad entre la variable a predecir y la mayoría de las features de entrada.

Lo recomendado es aplicar reducción de dimensionalidad para reducir la complejidad lo mayor posible y con ello evitar los tres problemas mencionados anteriormente.
