# Diferencia entre NumPy matrix y ndarray
Por Rodolfo Antonio Zea Posadas

Como punto de partida, previo a enfocarnos en las diferencias, definimos cada uno de los conceptos.

# NumPy matrix

Es una subclase de NumPy ndarray que nació con la naturaleza de realizar operaciones binarias y operaciones de álgebra lineal.

<b> Ejemplo de implementación: </b>

In [1]:
import numpy as np

a = np.matrix([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


# Numpy ndarray

Es la clase con la que NumPy define arreglos multidimensionales (n dimensiones), y homogéneos (cada elemento es del mismo tipo) que contienen elementos de tamaño fijo.

<b> Ejemplo de implementación: </b>

In [7]:
a = np.ndarray(shape=(2,2), dtype=int, order='F')
print(a)

[[1 3]
 [2 4]]


# Diferencias

La principal diferencia radica en el enfoque de cada uno de éstos. Mientras que matrix fue pensado para realizar operaciones binarias y de álgebra lineal, ndarray surgió como un estándar para operar con arreglos de múltiples dimensiones (1,2,3,..n). 

<b> Multiplicación de elementos de una matriz </b>

En el caso de los arreglos, para la multiplicación de los elementos de dos arreglos se hace mediante el operador * . Para el caso de las matrices, ha de usarse la función multiply

<b> Ejemplo: </b>

In [23]:
# Matrices
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])
print('Operación en matrices')
print(a)
print(b)
print('np.multiply(a,b)')
print(np.multiply(a,b))
print('\n')

# Arreglos
c = np.ndarray(shape=(2,2), dtype=int, order='F')
c[0][0] = 1
c[0][1] = 2
c[1][0] = 3
c[1][1] = 4

d = np.ndarray(shape=(2,2), dtype=int, order='F')
d[0][0] = 5
d[0][1] = 6
d[1][0] = 7
d[1][1] = 8

print('Operación en arreglos:')
print(a)
print(b)
print('c * d')
print(c * d)

Operación en matrices
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
np.multiply(a,b)
[[ 5 12]
 [21 32]]


Operación en arreglos:
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
c*d
[[ 5 12]
 [21 32]]


<b> Multiplicación de matrices </b>

En el caso de los arreglos, la multiplicación de matrices se hace mediante el operador * , mientras que para matrices se utiliza el operador @ .

<b> Ejemplo: </b>

In [28]:
print('Operación en matrices')
print('np.dot(a,b)')
print(np.dot(a,b))
print('\n')

# Arreglos
print('Operación en arreglos:')
print('c @ d')
print(c @ d)

Operación en matrices
np.dot(a,b)
[[19 22]
 [43 50]]


Operación en arreglos:
c @ d
[[19 22]
 [43 50]]


<b> Manejo de dimensiones </b>

Los arreglos pueden tener cualquier número entero positivo de dimensiones, sin embargo, las matrices siempre manejan dos dimensiones.

Esto puede verificarse cuando se trata de arreglos de una dimensión para cuando se utilizan matrices. En este caso, el arreglo se convierte en una matriz de 1XN o NX1 de dos dimensiones (1 y N).

<b> Constructor </b>

El constructor que se utiliza en la creación de arreglos recibe secuencias de python como inicializadores mientras que el constructor de una matriz utiliza un string como inicializador.

<b> Ejemplo: </b>

In [15]:
arreglo = np.ndarray(shape=(2,2), dtype=float, order='F')
print(arreglo)

matriz = np.matrix([[1, 2], [3, 4]])
print(matriz)

[[1.30551444e-311 1.97626258e-323]
 [6.95316046e-310             nan]]
[[1 2]
 [3 4]]


# Conslusión

A manera de conclusión puede decirse que en lugar de usar matrices, ScyPy recomienda el uso de arreglos (ya que todo tipo de operaciones de matrices puede hacerse con arreglos.

# Fuentes

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html?highlight=numpy%20matrix#numpy.matrix

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use

https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u